site_name: Axiom
site_url: https://axiom.voxelpi.net
repo_url: https://github.com/VoxelPi/Axiom-Wiki
repo_name: voxelpi/axiom-wiki
copyright: Copyright &copy; 2025 Oliver Seiter, Peter Smek
plugins:
  - search
  - tags
extra:
  generator: false
theme:
  name: material
  logo: assets/axiom.svg
  favicon: assets/axiom.svg
  icon:
    repo: fontawesome/brands/github
  homepage: https://axiom.voxelpi.net
  features:
    - navigation.sections
    - navigation.path
    - navigation.top
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
